CREATE TABLE Boards
(
	Id    UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Title NVARCHAR(255)    NOT NULL
);

CREATE TABLE Columns
(
	Id       UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	BoardId  UNIQUEIDENTIFIER NOT NULL,
	Title    NVARCHAR(255)    NOT NULL,
	Position INT              NOT NULL,
	CONSTRAINT FK_Columns_Boards FOREIGN KEY (BoardId) REFERENCES Boards (Id)
);

CREATE TABLE BoardRoots
(
	BoardId  UNIQUEIDENTIFIER NOT NULL,
	EntityId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_BoardRoots PRIMARY KEY (BoardId, EntityId),
	CONSTRAINT FK_BoardRoots_Boards FOREIGN KEY (BoardId) REFERENCES Boards (Id)
);

CREATE TABLE Placements
(
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Placements PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	EntityId UNIQUEIDENTIFIER NOT NULL,
	BoardId UNIQUEIDENTIFIER NOT NULL,
	ColumnId UNIQUEIDENTIFIER NOT NULL,
	Timestamp DATETIME2 NOT NULL,
	SortKey NVARCHAR(254) NOT NULL,

	CONSTRAINT FK_Placements_Columns
		FOREIGN KEY (ColumnId)
		REFERENCES Columns(Id),
	CONSTRAINT FK_Placements_Boards_BoardId 
		FOREIGN KEY (BoardId) 
		REFERENCES dbo.Boards(Id),
);

CREATE TABLE ColumnEdges
(
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ColumnEdges PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	FromColumnId UNIQUEIDENTIFIER NOT NULL,
	ToColumnId UNIQUEIDENTIFIER NOT NULL,
);